# Generated by Django 5.1.2 on 2024-10-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('departamento', models.CharField(max_length=100)),
                ('corregimiento', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(choices=[('Amazonas', 'Amazonas'), ('Antioquia', 'Antioquia'), ('Arauca', 'Arauca'), ('Atlántico', 'Atlántico'), ('Bolívar', 'Bolívar'), ('Boyacá', 'Boyacá'), ('Caldas', 'Caldas'), ('Caquetá', 'Caquetá'), ('Casanare', 'Casanare'), ('Cauca', 'Cauca'), ('Cesar', 'Cesar'), ('Chocó', 'Chocó'), ('Córdoba', 'Córdoba'), ('Cundinamarca', 'Cundinamarca'), ('Guainía', 'Guainía'), ('Guaviare', 'Guaviare'), ('Huila', 'Huila'), ('La Guajira', 'La Guajira'), ('Magdalena', 'Magdalena'), ('Meta', 'Meta'), ('Nariño', 'Nariño'), ('Norte de Santander', 'Norte de Santander'), ('Putumayo', 'Putumayo'), ('Quindío', 'Quindío'), ('Risaralda', 'Risaralda'), ('San Andrés y Providencia', 'San Andrés y Providencia'), ('Santander', 'Santander'), ('Sucre', 'Sucre'), ('Tolima', 'Tolima'), ('Valle del Cauca', 'Valle del Cauca'), ('Vaupés', 'Vaupés'), ('Vichada', 'Vichada')], default='Antioquia', max_length=50)),
                ('corregimiento', models.CharField(default='', max_length=100)),
                ('forma', models.CharField(default='', max_length=100)),
                ('descripcion', models.TextField(default='')),
                ('altura_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('autor', models.CharField(default='Desconocido', max_length=100)),
                ('complejo_ceramico', models.CharField(choices=[('Capulí', 'Capulí'), ('Tuza', 'Tuza'), ('Piartal', 'Piartal')], default='Capulí', max_length=50)),
                ('tecnica_decorativa', models.CharField(default='', max_length=100)),
                ('acabado_superficie', models.CharField(choices=[('Alisado', 'Alisado'), ('Baño', 'Baño'), ('Bruñido', 'Bruñido'), ('Engobe', 'Engobe'), ('Erosionado', 'Erosionado'), ('Pulido', 'Pulido'), ('Alisado y Bruñido', 'Alisado y Bruñido'), ('Alisado y Baño', 'Alisado y Baño'), ('Alisado, Bruñido y Pulido', 'Alisado, Bruñido y Pulido'), ('Alisado y Englobe', 'Alisado y Englobe'), ('Alisado, erosionado y Englobe', 'Alisado, erosionado y Englobe'), ('Alisado y erosionado', 'Alisado y erosionado'), ('Alisado y pulido', 'Alisado y pulido')], default='Alisado', max_length=50)),
                ('tecnica_manufactura', models.CharField(choices=[('Rollos y Modelado', 'Rollos y Modelado'), ('Pellizcado y Modelado', 'Pellizcado y Modelado'), ('Colombín y Modelado', 'Colombín y Modelado'), ('Torneado', 'Torneado'), ('Moldeado', 'Moldeado')], default='Moldeado', max_length=50)),
                ('textura_pasta', models.CharField(choices=[('Compacta', 'Compacta'), ('Friable', 'Friable'), ('Granular', 'Granular'), ('Laminar', 'Laminar'), ('Porosa', 'Porosa')], default='Compacta', max_length=50)),
                ('coccion', models.CharField(choices=[('Oxidante', 'Oxidante'), ('Reducida', 'Reducida'), ('Mixta', 'Mixta')], default='Oxidante', max_length=50)),
                ('color_pasta', models.CharField(default='', max_length=50)),
                ('composicion_desgrasante', models.CharField(default='', max_length=100)),
                ('tamano_desgrasante', models.CharField(choices=[('Muy fino', 'Muy fino'), ('Fino', 'Fino'), ('Medio', 'Medio'), ('Grueso', 'Grueso')], default='Medio', max_length=50)),
                ('imagen', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('enlace', models.URLField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('imagen', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TecnicaCeramica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('tipo', models.CharField(blank=True, choices=[('tecnica_manufactura', 'Técnica manufactura'), ('tipologia_ceramica', 'Tipología cerámica'), ('decoracion_ceramica', 'Decoración cerámica'), ('coccion_ceramica', 'Cocción cerámica')], max_length=30, null=True)),
            ],
        ),
    ]
