# Generated by Django 5.1.2 on 2024-10-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_imagen_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
