# Generated by Django 5.1.2 on 2024-10-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_imagen_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='acabado_superficie',
            field=models.CharField(choices=[('Alisado', 'Alisado'), ('Baño', 'Baño'), ('Bruñido', 'Bruñido'), ('Engobe', 'Engobe'), ('Erosionado', 'Erosionado'), ('Pulido', 'Pulido'), ('Alisado y Bruñido', 'Alisado y Bruñido'), ('Alisado y Baño', 'Alisado y Baño'), ('Alisado, Bruñido y Pulido', 'Alisado, Bruñido y Pulido'), ('Alisado, Bruñido, erosionado y Pulido', 'Alisado, Bruñido, erosionado y Pulido'), ('Alisado y Englobe', 'Alisado y Englobe'), ('Alisado, erosionado y Englobe', 'Alisado, erosionado y Englobe'), ('Alisado y erosionado', 'Alisado y erosionado'), ('Alisado y pulido', 'Alisado y pulido')], default='Alisado', max_length=50),
        ),
    ]
