"""
Django settings for Tesis project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(1#aws4mm9oyf6qw!gs221g)g)kr3byeg&3x*c!9^pe595mbkc'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

X_FRAME_OPTIONS = 'DENY'  # Protege contra ataques de clickjacking
SECURE_BROWSER_XSS_FILTER = True  # Habilita el filtro XSS del navegador
# Configuración de cookies seguras
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True  # Solo enviar cookies a través de HTTPS
SESSION_COOKIE_HTTPONLY = True  # No accesible a través de JavaScript
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_SAMESITE = 'Lax'  # Previene el envío de cookies en solicitudes entre sitios
SESSION_COOKIE_AGE = 18000  # 5 horas

#Encabezados HSTS
SECURE_HSTS_SECONDS = 31536000  # 1 año en segundos
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'sslserver',
    'axes',
    #'csp',
    'myapp',  # Tu aplicación
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'myapp.middleware.RateLimitMiddleware',
    'axes.middleware.AxesMiddleware',
    #'csp.middleware.CSPMiddleware',
    'django_otp.middleware.OTPMiddleware',  # Middleware para OTP
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # Asegúrate de que este esté presente
    'django.contrib.auth.backends.ModelBackend',  # Si usas el backend por defecto
]
#Twilio para autenticacion FMA
TWILIO_VERIFY_SID = os.environ.get('TWILIO_VERIFY_SID', 'VA21c11f35407e77eb8c7a014b28139bd5')
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_VERIFY_SID', 'SKffaf4556b0a6e273da115178c26aea78')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '768e12ad5c509566ec47a7c74a8839fc')

#Axes para validar los intentos de login
AXES_FAILURE_LIMIT = 5  # Número máximo de intentos fallidos antes de bloquear
AXES_COOLOFF_TIME = 1  # Tiempo en horas para el cual se bloqueará la cuenta
AXES_DISABLE_SUCCESS_LOGGING = True  # No registrar inicios de sesión exitosos

# Configuración de CSP 
#CSP_DEFAULT_SRC = ("'self'",)
#CSP_SCRIPT_SRC = (
 #   "'self'",
 # "https://code.jquery.com",
   # "https://cdn.jsdelivr.net",
   # "https://stackpath.bootstrapcdn.com",
#)
#CSP_STYLE_SRC = (
 #   "'self'",
  #  "https://stackpath.bootstrapcdn.com",
#)
#CSP_IMG_SRC = (
 #   "'self'",
  #  "data:",  # Permitir imágenes embebidas como data URIs
   # "https://*.tile.openstreetmap.org",  # Si usas mapas de Leaflet, permite sus tiles
#)
#CSP_CONNECT_SRC = (
 #   "'self'",
  #  "https://newsapi.org",
#)


ROOT_URLCONF = 'Tesis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Tesis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'myapp/static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuración de logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR,'logs', 'debug.log'),
            'formatter': 'verbose'
        },
    },
    'formatters': {
        'verbose': {
            'format': '%(asctime)s %(levelname)s %(module)s %(process)d %(thread)d %(message)s'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,

        },
    },
}



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

